name: task - validate commit on master
on:
  push:
    branches: [ unit-test-pipeline-setup ]

jobs:
  basic_job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Setup actions.
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

#      - name: Generate AAR and APK files
#        if: always()
#        run: ./gradlew assembleDebug

      - name: Run Unit Tests
        if: always()
        run: ./gradlew jacocoTestReport

#      - name: Upload AAR files
#        if: always()
#        uses: actions/upload-artifact@v2
#        with:
#          name: artifacts.zip
#          path: |
#            app/build/outputs/apk/debug/app-debug.apk
#            FindingAlFalcone/build/outputs/aar
